### ISSUE TITLE
Crash hard when the user tries get or put before `ready` is emitted?

### ISSUE THREAD

**Issue by paulkernfeld** [feross/bittorrent-dht#102]
Could I make a PR that throws an error if the user calls put or get too soon? This was tripping me up, and I think it was also causing [a problem](https://github.com/maxogden/dhtkv/pull/5) with dhtkv.

Is there any legit use case for calling get or put before ready is emitted? For me, it caused the calls to fail while appearing to succeed.

**Comment by mafintosh** [comment]
As of 6.0 you shouldnt have to wait for ready any more. The bootstrap table is now being build in the background reducing latency a lot of cmd line tools like dhtkv. Could you share a test case that works if you wait for ready but fails if you dont? Then we'll try to fix it :)

**Comment by paulkernfeld** [comment]
I will try to write a test case for this. I think I'm going to start with a live test case that replicates the problem I described in maxogden/dhtkv#5.  Then maybe I can move onto a proper unit test if that works.

**Comment by paulkernfeld** [comment]
All right, here is a PR for a live test that demonstrates the problem: feross/bittorrent-dht#103

**Comment by mafintosh** [comment]
Thanks. Could reproduce. I think i know what the problem is. Will push a fix later today.

**Comment by mafintosh** [comment]
@paulkernfeld actually i cannot reproduce after all. i was running the wrong test. is this reproducible for you?

**Comment by mafintosh** [comment]
note that creating two DHT instances right after each other might make the bootstrap nodes and subsequent nodes close to the key not reply as a DDOS protection.

**Comment by mafintosh** [comment]
@paulkernfeld i think i found the bug. basically queries that we're being buffered would almost always fail because of a bug in the k-rpc module. more queries were being buffered when you weren't waiting for `ready` to fire. the should be fixed in latest version of k-rpc and bittorrent-dht. let me know if it works
