### ISSUE TITLE
Docs on how to verify GETs of mutable key-value pairs

### ISSUE THREAD

**Issue by lmatteis** [feross/bittorrent-dht#105]
So as far as I understand from the BEP44 spec, the key returned by a mutable PUT is actually the hash of the public key. Is there documentation on which hashing function is used? Perhaps there could be a small example on how one can verify that a mutable GET returns the valid actual data. I imagine one first needs to SHA-1 the returned public-key and see whether that corresponds to the actual key used for the GET of such content. Next one can verify using the signature, contents and public-key.

However a more formal in-code explanation would be useful!

**Comment by mafintosh** [comment]
The dht module will verify the values returned from GET for you. You can see the verification code here, https://github.com/feross/bittorrent-dht/blob/master/client.js#L236-L247

**Comment by mafintosh** [comment]
actually returning an error is tricky as we don't know that it is a mutable request until we verify the response. i'll add some debug statements instead.

**Comment by lmatteis** [comment]
Thanks so it's all automatic! Sweet
