### ISSUE TITLE
How to get "hash" from just public key

### ISSUE THREAD

**Issue by lmatteis** [feross/bittorrent-dht#109]
From the BEP44 spec it seems that the "hash" for mutable content is the SHA1 hash of public key you use to sign it. If I `dht.put` something using this public key `ddbed2b032f8b22f6c4ecae843ad796c1b5886e3e7817b58f4c941deb5bfb05f`, I get back this hash `c3bcf073c950cc07389dbdedb0d404a69726ccbc`.

However, if I SHA1 the same public key I get `d6ae012c02ac3768e8a76edc4198ecf7e30cbbb8` rather than the hash from before.

Any idea what I'm missing? Thanks!

**Comment by mafintosh** [comment]
```
var k = Buffer('ddbed2b032f8b22f6c4ecae843ad796c1b5886e3e7817b58f4c941deb5bfb05f', 'hex')
crypto.createHash('sha1').update(k).digest('hex')
```

prints

```
c3bcf073c950cc07389dbdedb0d404a69726ccbc
```

**Comment by mafintosh** [comment]
ah it seems you're hashing the hex string instead of the buffer. the above way is the correct way.

**Comment by lmatteis** [comment]
Thanks!
