### ISSUE TITLE
How do I find out what data my node is storing?

### ISSUE THREAD

**Issue by lmatteis** [feross/bittorrent-dht#112]
I know `dht.toArray()` can be used to see the nodes I'm connected to (so that I can bootstrap across client shutdowns). What I'm wondering though is, where is the actual data I'm storing saved? I imagine it's kept in memory and simply thrown out when I close my process.

For instance, imagine someone doing a `.put()` and I happen to be the closest node and I therefore store this item.

**Comment by lmatteis** [comment]
I've dug in the code a little and found an `_onput` method: https://github.com/feross/bittorrent-dht/blob/master/client.js#L438

Furthermore it seems to store them in a `this._values` LRU structure. Should this be allowed to be accessed from the API? Maybe a `getValues()` public method?

**Comment by feross** [comment]
I'm cool with exposing this. @mafintosh thoughts?

I think we should get rid of `toArray()` entirely and just have `toJSON()` that has two properties:

```json
{
  "nodes": [],
  "values": {}
}
```

**Comment by mafintosh** [comment]
i'm fine with that

**Comment by feross** [comment]
Sent a PR adding this: https://github.com/feross/bittorrent-dht/pull/113

**Comment by feross** [comment]
This was released in v7.0.0.
