### ISSUE TITLE
dht.get always returns null for mutable content

### ISSUE THREAD

**Issue by mihv** [feross/bittorrent-dht#129]
Trying to get mutable content examples working, but dht.get always returns null without any error.

Setting content code:

```javascript
var ed = require('ed25519-supercop');
var keypair = ed.createKeyPair(ed.createSeed());

var value = new Buffer(100).fill('helloworld'); // the payload you want to send
var opts = {
    k: keypair.publicKey,
    seq: 0,
    v: value,
    sign: function (buf) {
        return ed.sign(buf, keypair.publicKey, keypair.secretKey)
    }
};

var DHT = require('bittorrent-dht');
var dht = new DHT();

dht.listen(function () {
    console.log('dht is listening');
});

dht.on('ready', function() {
    console.log('dht is ready');
    dht.put(opts, function (err, hash, nodesAccepted) {
        console.error('error=', err);
        console.log('hash=', hash.toString('hex'), 'nodes accepted:', nodesAccepted);
    })
});
```
Then output is something like this:
```
dht is listening
dht is ready
error= null
hash= 87283a9f5e7bb584b367a95fa01577a8e4f0a730 nodes accepted: 14
```

Then I leave this script launched and use the same hash to launch the second script:

```javascript
var DHT = require('bittorrent-dht');
var dht = new DHT();

dht.listen(function() {
    console.log('dht is listening:');
});

dht.on('ready', function () {
    console.log('dht is ready');
    dht.get('87283a9f5e7bb584b367a95fa01577a8e4f0a730', function (err, res) {
        if (err) {
            console.error('failed to get reply:', err);
        } else {
            console.log('get reply:', res);
        }
    });
});
```
The response is always null but without any error:
```
dht is listening:
dht is ready
get reply: null
```

I also tried many variations with exact UDP ports (which were forwarded), also with setInterval where put and get executed periodically in the both scripts, tried to launch the second script on another computer with different external IP, but dht.get reply was always null.

**Comment by mihv** [comment]
By the way I used node v4.4.4 on 64-bit debian linux for the "put" script and the "get" was launched on the same machine first and then on 64-bit Windows with node v4.4.3. The results were always the same.

**Comment by mihv** [comment]
Sorry I didn't checked closed issues before posting a new one:
The problem was resolve in the https://github.com/feross/bittorrent-dht/issues/104
The answer is to use on the "get" side:
```javascript
var ed = require('ed25519-supercop');
var dht = new DHT({verify: ed.verify});
```

Probabbly it's a good idea to update readme in order to reflect this important point. Also it would be great if some error is generated in similar case.

**Comment by mafintosh** [comment]
@mihv you wanna send a PR that adds that? :)

**Comment by feross** [comment]
@mihv Yes, PR welcome!

**Comment by mihv** [comment]
@mafintosh, feross Guys, sorry for the delay. I sligtly updated the readme in order to notice this very important thing and created a pull request.

By the way, thank you for writting such great software, your work is invaluable!
