### ISSUE TITLE
dht.toJSON().values never gets populated

### ISSUE THREAD

**Issue by kurttomlinson** [feross/bittorrent-dht#134]
I've been running a DHT node with this package for several hours now, but the dht node never seems to store any values. Here's my code:

```
...

console.log = function(data) {
   if(arguments.length) {
      var timestamp = '[' + new Date().toUTCString() + ']';
      this.logCopy(timestamp, arguments);
   }
};

...

dht.on('announce', function(peer, infoHash) {
  console.log("announce "+node_index+": "+peer.host + ':' + peer.port+' : '+infoHash.toString('hex'));
  console.log("values stored by node #" + node_index)
  console.log(dht.toJSON().values);
});

...
```
And here's my output:

> [Tue, 26 Jul 2016 13:32:28 GMT] { '0': 'announce 0: 128.28.XXX.XXX:XXXXX : f2d7dd2727d807050edc56fb1c28XXXXXXXXXXXX' }
> [Tue, 26 Jul 2016 13:32:28 GMT] { '0': 'values stored by node #0' }
> [Tue, 26 Jul 2016 13:32:28 GMT] { '0': {} }

Why is `dht.toJSON().values` always empty?

**Comment by feross** [comment]
If you're behind a firewall or a NAT, then no peers will be able to connect to you and store values. That's my bet for what's going on here.

**Comment by kurttomlinson** [comment]
I don't think that's the problem. My firewall is disabled and the PC I'm running this on is DMZed in my router's settings.

Before I DMZed my PC, bittorrent-dht never received any announces. Now, I'm receiving announces, but no values are being stored.

How is it possible to receive announces while not receiving any values?

**Comment by feross** [comment]
When you receive announces, those are peer IP addresses, but that data is not important to persist so `toJSON` doesn't return it. The `values` key is for storing extra additional, much larger data in the DHT, via an extension called [BEP44](http://www.bittorrent.org/beps/bep_0044.html). In order to enable that, you need to follow the instructions in the readme and initialize the DHT like this:

```js
var ed = require('ed25519-supercop')
var dht = new DHT({ verify: ed.verify })
```
