### ISSUE TITLE
TypeError thrown in toJSON after put query is received

### ISSUE THREAD

**Issue by xuset** [feross/bittorrent-dht#137]
If a peer receives a put query, all subsequent calls to toJSON throw a TypeError. This is because toJSON iterates over the stored values and calls `value.id.toString('hex')` but when the put query is received the `id` is not stored. It seems both mutable and immutable values are affected by this. However, the peer that initiated the put does store the `id` value so toJSON works as expected.

Stack trace:
```
TypeError: Cannot read property 'toString' of undefined
    at bittorrent-dht/client.js:120:19
    at Array.forEach (native)
    at DHT.toJSON (bittorrent-dht/client.js:116:35)
```

If you want a can submit a PR with the fix? 👍

**Comment by feross** [comment]
Good catch. Yes, please send a PR!

(Bonus: Add a test that fails before your change, but passes afterwards.)

Thanks!!
