### ISSUE TITLE
Event for FIND-VALUE Requests

### ISSUE THREAD

**Issue by mohit-oviyum** [feross/bittorrent-dht#141]
In bittorrent-dht I see there is option to specify host, if set host = true. Will it behave as real DHT node? Will it get FIND-VALUE requests from other nodes ? Is there any event to listen when node gets FIND-VALUE request from other node?

Sorry for opening an issue for question.

**Comment by mafintosh** [comment]
It always behave as a real dht node, storing values etc. I don't think we emit an event right now when you are returning values but we should indeed do that

**Comment by mafintosh** [comment]
I've added a PR here for some more events, https://github.com/feross/bittorrent-dht/pull/142. Take a look if that would fix your issue.

**Comment by mohit-oviyum** [comment]
Thanks! 'get' event will solve my problem.

**Comment by mafintosh** [comment]
7.4.0 now emits `announce_peer`, `get_peers`, `get`, and `put` when the requests are received.
