### ISSUE TITLE
Getting error: 'No nodes to query' when storing content

### ISSUE THREAD

**Issue by ogisan** [feross/bittorrent-dht#147]
I'm creating a new DHT and with opts = {bootstrap: false, verify: ed.verify}, I then proceed to store a mutable value using put() but get back an error 'No nodes to query'. 

If I set bootstrap: true, then everything works fine, however, I need this to work locally with my own bootstrap server and I can't figure out why it throws that error.

**Comment by ogisan** [comment]
After looking into it, it seems that the error fires even when the PUT is successful. The error could be made clearer but it's not a bug.

**Comment by cubuspl42** [comment]
@ogisan I don't understand. So you are saying that the `Error` is thrown when everything went fine? How is library user is supposed to handle such situation?
