### ISSUE TITLE
test if peer is webrtc compatible

### ISSUE THREAD

**Issue by chovy** [feross/bittorrent-dht#151]
I'm using this code to get peers:

      dht.lookup(data.infohash, (err, peers) => {
        data.peers = peers; // eg: 10
        resolve(data);
      });

Is there anyway to check the `peers` to see if any support webrtc/webtorrent?

**Comment by feross** [comment]
The peers found in the DHT will always be `ip:port` peers, never WebRTC peers. Technically, the client listening on the `ip:port` could also support WebRTC, but there's no way to find that out.

**Comment by chovy** [comment]
Its not even possible to try connecting over webrtc somehow and see if it succeeds?

**Comment by feross** [comment]
No, an IP and port is not enough to connect over WebRTC. I suggest reading about how WebRTC works.
