### ISSUE TITLE
Can I use bittorrent-dht to connect to a peer?

### ISSUE THREAD

**Issue by matteomonti** [feross/bittorrent-dht#153]
First of all: this project is awesome. I am testing a sketch of a new cryptocurrency protocol, and I would like to use bittorrent-dht to connect my nodes in a peer to peer fashion. I know I can use `dht.announce` and `dht.lookup` to setup rendezvous and let nodes know about each others' ip and port. I also know that when I omit the port in `dht.announce`, the external port I am communicating from is used, which is nice in the case where I am behind some NAT that changes my external ports.

Now, when I get a callback from `dht.on('peer', ...)`, I obviously only get an ip and a port. Now, I would like to actually connect to that peer. How can I achieve this? If I omitted the port, the socket behind the port I received is going to be already used by the `dht` object. By going through it I found out I can technically hijack `dht._rpc.socket.socket`, which looks like an UDP socket from which I can send and receive packets. But I wouldn't want to interfere with the protocol.

So is there a nice way to get an actual connection between two peers, once they have discovered each other and are willing to connect?

**Comment by feross** [comment]
The DHT listens on UDP. You can have your peers also listen on TCP on the same port, and connect on that. That's what WebTorrent does :)
