### ISSUE TITLE
destroy an in-progress `lookup`

### ISSUE THREAD

**Issue by arestov** [feross/bittorrent-dht#41]
I want to download 5 torrents by magnet links in same time. I suppose that I should use 1 `bittorrent-dht` instance instead of 5 (please fix me if this wrong).

So i will do following
```
var infoHashes = [..., ..., ...];
//infoHashes.length == 5

var table = dht();

table.on('peer', function(peer, infoHash){
	//do something
});
table.on('ready', function() {
	infoHashes.forEach(function(infoHash){
		table.lookup(infoHash);
	})
});
```
I want to completely stop downloading infoHashes[2]. What I need to do to destroy lookup for `infoHashes[2]`?

**Comment by mafintosh** [comment]
@Ivshti you fixed this right?

**Comment by Ivshti** [comment]
@mafintosh I think so. .lookup returns a function that can be used to close

**Comment by mafintosh** [comment]
@arestov o/
