### ISSUE TITLE
Use KRPC for handling messages

### ISSUE THREAD

**Issue by moshest** [feross/bittorrent-dht#48]
Full API here:
https://github.com/DevelopmentIL/krpc

**Comment by feross** [comment]
krpc looks neat. Why did you write it? Seems like a really specific use case and we already handle it just fine. Did you write it specifically for this module to use?

**Comment by moshest** [comment]
I write it for other module that I working on. I thought you might want to use it as well. It helps keep things on order.

**Comment by feross** [comment]
Thanks for sharing, but I don't see any benefit to using this right now.
