### ISSUE TITLE
lookup with 3+ DHTs fails occasionally (non-deterministically)

### ISSUE THREAD

**Issue by mvayngrib** [feross/bittorrent-dht#50]
Edit: I guess for 2 it doesn't work because nodes don't know their own ips

I wanted to see if how many DHT instances with each other in their routing tables were enough to do announce + successful lookup. I hoped 2, but as a DHT node never returns itself as a peer, this appears to be impossible. Is this by design? 4+ are usually enough, but not always, which makes me think there's some race condition.

    test('test announce+lookup with different quantities of DHTs', function (t) {
      var from = 2;
      var to = 10;

      t.plan(to - from + 1);

      for (var i = from; i <= to; i++) {
        (function(numInstances) {      
          findPeers(numInstances, t, function(err) {
            if (err) t.error(err)
            else t.pass('Success with ' + numInstances + ' instances')
          });
        })(i)
      }
    })

    /**
     *  Initialize [numInstances] dhts, have one announce an infoHash and another perform a lookup
     *  Times out after a while
     */
    function findPeers(numInstances, t, cb) {
      var timeoutId = setTimeout(function() {
        cleanup(new Error('Timed out for ' + numInstances + ' instances'))
      }, 5000);

      var infoHash = common.randomId()
      var dhts = [];

      for (var i = 0; i < numInstances; i++) {
        var dht = new DHT({ bootstrap: false });
        dhts.push(dht);
        common.failOnWarningOrError(dht, t);
      }

      // wait till everyone's listening
      parallel(dhts.map(function(dht) {
        return function(cb) {
          dht.listen(function(port) {
            cb(null, port);
          })
        }
      }), function(err, ports) {
        // add each other to routing tables
        makeFriends(dhts);
        dhts[0].announce(infoHash, 9999, function() {
          dhts[1].lookup(infoHash)      
        })
      })

      dhts[1].on('peer', function(addr, hash) {
        if (hash === infoHash.toString('hex')) {
          cleanup()
        }
      })

      function cleanup(err) {
        parallel(dhts.map(function(dht) {
          return dht.destroy.bind(dht)
        }), function() {
          clearTimeout(timeoutId)
          cb(err)
        })
      }
    }

    /**
     *  Adds every dht in [dhts] to every other dht's routing table
     */
    function makeFriends(dhts) {
      for (var i = 0; i < dhts.length; i++) {
        for (var j = i + 1; j < dhts.length; j++) {
          var d1 = dhts[i]
          var d2 = dhts[j]
          d1.addNode('127.0.0.1:' + d2.port, d2.nodeId)
          d2.addNode('127.0.0.1:' + d1.port, d1.nodeId)
        }
      }
    }

**Comment by mvayngrib** [comment]
if you want a more controlled test (it may take a few tries till it fails)

    test('test announce+lookup with 3 DHTs', function (t) {
      t.plan(1);

      findPeers(3, t, function(err) {
        if (err) t.error(err)
        else t.pass()
      })
    })

**Comment by mvayngrib** [comment]
#51 seems to fix it

**Comment by feross** [comment]
>  a DHT node never returns itself as a peer. Is this by design?

The reason we don't add ourselves to the table is so we don't accidentally try to query ourselves. As long as that constant is preserved, it would be okay for a DHT node to return itself is response to a lookup.
