### ISSUE TITLE
BEP44: storing arbitrary data in the DHT

### ISSUE THREAD

**Issue by substack** [feross/bittorrent-dht#60]
BEP44 is very exciting because it introduces mutable content signed with a public key. With mutable hashes, applications like twitter-style feeds can be built on the DHT which may prove very useful for projects like [ssb](https://github.com/ssbc). libtorrent and utorrent already have support for dht_store but I'm not sure if anybody is using this feature in the wild yet.

I started implementing this BEP on top of the bittorrent-client plugin system, but it doesn't make much sense to implement on top of bittorrent-client because couples strongly with the dht implementation.

* http://bittorrent.org/beps/bep_0044.html
* http://www.libtorrent.org/dht_store.html

**Comment by grncdr** [comment]
me and @ehd are also quite interested in this. I'm still pretty ignorant of how this code is structured, but... given that we're talking about a DHT protocol extension, it seems like it would make sense to implement it directly here?

@substack if you are already working on this maybe we can collaborate or I can just provide you some $$ assistance? For me the goal would is having a browser nodes be able to bootstrap into a DHT for sharing javascript code.

**Comment by ehd** [comment]
[BEP44](http://bittorrent.org/beps/bep_0044.html) mentions a value size limitation of 1000 bytes, is this going to be a problem? A mutable value could always be a reference to something bigger, like an infoHash. But for immutable values 1K seems to be quite limiting for general purpose usage. Maybe bigger values could be split up into multiple values stored as trees, although there's probably negative performance implications for this.

For the code storage use case @grncdr mentioned: Most content is content-addressable blobs of source code. Ideally those blobs would be stored in the DHT with local nodes (my other computer, a node process on my computer) keeping blobs in persistent storage ready for other peers.

**Comment by substack** [comment]
I'll be hacking on this on the plane ride to Uruguay today. I'll report back with progress. It doesn't seem very complicated implementation-wise.

**Comment by substack** [comment]
First leg of the flight, first chunk of progress: immutable get/put is working: https://github.com/substack/bittorrent-dht/tree/dht-store

Next I'll get mutable get/put working.

**Comment by ehd** [comment]
Really nice!

> I don't think the 1k limit will be such a problem for my use-case, since you can always point to an immutable hash that points to other immutable hashes as a merkle DAG. That might not have great latency but there are probably ways to pre-fetch content.

Makes sense. I'm curious how much the announce overhead is going to be for many small values that make up a bigger value. As far as I understood DHT peers still need to announce all the keys that they possess.

**Comment by substack** [comment]
Mutable get/put work now. I just need to implement the error codes and seq/cas checks.

**Comment by substack** [comment]
PR sent! https://github.com/feross/bittorrent-dht/pull/61

**Comment by substack** [comment]
Some possible problems with BEP44: https://gist.github.com/substack/eadd13302d785dc13aac#file-results-markdown

**Comment by substack** [comment]
Potential problems aside, this patch has been merged into 4.0.0.
