### ISSUE TITLE
_addNode should handle 'ping' from nodes kbucket

### ISSUE THREAD

**Issue by mvayngrib** [feross/bittorrent-dht#68]
should be pretty straightforward to implement

it might make

```js
test('`node` event fires for each added node (10000x)', function (t) {
```

excruciatingly long

**Comment by feross** [comment]
I don't understand what this issue is asking for. @mvayngrib Can you clarify?

**Comment by mvayngrib** [comment]
sure, currently addNode issues self.nodes.add(newNode), and possibly fails (the self.nodes bucket emits 'ping').

from k-bucket/index.js:

```js
// we are not allowed to split the bucket
// we need to ping the first self.numberOfNodesToPing
// in order to determine if they are alive
// only if one of the pinged nodes does not respond, can the new contact
// be added (this prevents DoS flodding with new invalid contacts)
self.root.emit('ping',
    self.bucket.slice(0, self.numberOfNodesToPing),
    contact);
```

I'm just saying we should implement what's described in the comment.

**Comment by feross** [comment]
Ah, gotcha. There's already an issue for this. https://github.com/feross/bittorrent-dht/issues/20

Fixing this issue would make the DHT work better if it runs for a long time. PR welcome :)

**Comment by mvayngrib** [comment]
oops, my bad

**Comment by feross** [comment]
No problem :)
