### ISSUE TITLE
Do now throw, are throw? 

### ISSUE THREAD

**Issue by aaron-goshine** [feross/bittorrent-dht#78]
I was just reading through the code and I notice that there were lots of error handling in the code. nice but Isn't it frown upon to throw errors in `npm` packages.. in stead you should past it as the first argument of the callback.

**Comment by mafintosh** [comment]
the errors thrown are all configuration errors which you _should_ throw since your program is using this module wrong. there was a good article about this a while ago - i'll see if i can find it

**Comment by mafintosh** [comment]
https://www.joyent.com/developers/node/design/errors

**Comment by feross** [comment]
Yes, what @mafintosh said is correct. 

Programmer errors that are known at configuration-time *should* be thrown so they're detected as soon as possible by the programmer. Once you're using the module correctly, you don't have to worry about thrown errors at runtime. All runtime errors will be passed as the first argument to the callback.
