### ISSUE TITLE
Ability to pause/resume lookup

### ISSUE THREAD

**Issue by Ivshti** [feross/bittorrent-dht#92]
The rationale here is that in many cases we end up with more peers queued than we can ever need, so in that case we don't want to consume any more traffic for the DHT.

@mafintosh's concern about this is related to announcing, but we would have already announced ourselves in most cases

------

alternatively, if this is getting too complex, we can just have an abort logic on the .lookup, by returning false in onreply

**Comment by feross** [comment]
Fixed in #93
