### ISSUE TITLE
peer lookup accuracy ?

### ISSUE THREAD

**Issue by elBarkey** [feross/bittorrent-dht#98]
```javascript
var net = require("net");
var DHT = require("bittorrent-dht");
var dht = new DHT();
var server = net.createServer();
var infoHash = crypto.createHash("sha1").update("mybtdhtidtest101").digest("hex");

server.listen(function(){
    var port = server.address().port;
    dht.on('ready', function() {
        dht.announce(infoHash, port,function(){
            dht.lookup(infoHash);
        });
    });
    console.log('server listening on %s',port);
});

dht.on('peer', function(peer, infoHash, from) {
    console.log('found potential peer ' + peer.host + ':' + peer.port + ' through ' + from.address + ':' + from.port);
// it's never found any correct ip:port of machineA/B/C
});
```

The code above executed on 3 machine that has its own public ip.
But each of them never found each other, sometime it founds the ip address, but wrong port.
Why this happened ?

**Comment by mafintosh** [comment]
could you check if announce returns an error?

**Comment by mafintosh** [comment]
i also just tried your snippet and it worked on my computer fine for me. has this worked with previous version of bittorrent-dht on your servers?

**Comment by elBarkey** [comment]
@mafintosh 
announce doesn't returns any error, i just saw some [Error: Unexpected transaction id: *num] on dht.on('warning') event.

after hours of confussion, i leave them turned off
then i tried it again & it works fine on first run.

affter some inspection, the problem only happen if the 3 machines restarted the code multiple times.
if it restarted 10 times or more in sort of time, peer event just shows only previous announced peer info.
i also tried dht.lookup on dht.on('announce')  event. but still, the newer peer info never shown up until i leave it off for a few hours.

**Comment by mafintosh** [comment]
@elBarkey ah if you restart a bunch of times there is a good chance other peers will drop your announces as a form of ddos protection.

**Comment by feross** [comment]
I agree with @mafintosh – this sounds like other DHT nodes guarding against DDOS.

Btw, you can ignore messages from the `'warning'` event – they're just for internal debugging.
